Amad, Francis Jalen

3rd Quarter Exam : Solving Systems of Equations Using Matrix Inverse

Part 1: Theory

In [2]:
import numpy as np

# Step 1: Define the matrix A (5x5) and vector B (5x1)
A = np.array([[3, 2, -1, 0, 0],
              [2, -1, 3, 0, 0],
              [1, 2, 4, 3, 0],
              [0, 1, -2, 2, 1],
              [0, 0, 3, 1, 4]])

B = np.array([1, 2, 3, 4, 5])

# Step 2: Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Step 3: Calculate the solution vector X
X = np.dot(A_inv, B)

# Step 4: Display the solution
print("The solution vector X is:")
print(X)

The solution vector X is:
[ 0.9057971  -0.99275362 -0.26811594  1.7173913   1.02173913]


Part 2: Application to Real-World Computer Science Problem

Part 3: Step-by-Stel Instructions

In [4]:
# Step 1: Define the coefficient matrix A (5x5 matrix)
A = np.array([
    [3, 2, 1, 1, 0],
    [1, 4, 2, 0, 1],
    [2, 3, 4, 1, 0],
    [1, 1, 3, 5, 0],
    [0, 1, 2, 4, 3]
])

# Step 2: Define the constant matrix B (5x1 matrix)
B = np.array([100, 150, 120, 110, 140])

# Step 3: Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Step 4: Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Step 5: Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    # Step 6: Display the solution (unknowns)
    print("Solution (Unknowns):")
    print(X)

Determinant of A: 277.0000000000002
Solution (Unknowns):
[ 7.36462094 32.23826715 -1.62454874 15.05415162 16.93140794]


Part 4: Practice Problems

Problem 1

In [14]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [2, 1, -1],
    [-1, 3, 2],
    [1, -2, 4]
])

# Define the constants vector b
b = np.array([5, 6, 7])

# Check if matrix is invertible
det = np.linalg.det(A)
print(f"Determinant of matrix A: {det:.2f}")

if det != 0:
    # Calculate inverse of A
    A_inv = np.linalg.inv(A)

    # Solve for x using x = A^(-1)b
    x = np.dot(A_inv, b)

    print("\nSolution:")
    print(f"x₁ = {x[0]:.2f}")
    print(f"x₂ = {x[1]:.2f}")
    print(f"x₃ = {x[2]:.2f}")

    # Verify the solution
    print("\nVerification:")
    verification = np.dot(A, x)
    print("Ax =", verification)
    print("b  =", b)
    print("\nIs solution correct?", np.allclose(verification, b))
else:
    print("Matrix is not invertible!")

Determinant of matrix A: 39.00

Solution:
x₁ = 2.64
x₂ = 1.62
x₃ = 1.90

Verification:
Ax = [5. 6. 7.]
b  = [5 6 7]

Is solution correct? True


Problem 2

In [13]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [5, 3, 1, 1, 0],
    [4, 6, 2, 0, 1],
    [2, 7, 3, 1, 0],
    [1, 2, 4, 5, 0],
    [3, 4, 5, 0, 6]
])

# Define the constants vector b
b = np.array([200, 300, 150, 120, 250])

# Check if matrix is invertible
det = np.linalg.det(A)
print(f"Determinant of matrix A: {det:.2f}")

if det != 0:
    # Calculate inverse of A
    A_inv = np.linalg.inv(A)

    # Solve for x using x = A^(-1)b
    x = np.dot(A_inv, b)

    print("\nSolution (Data flow through each connection):")
    for i, flow in enumerate(x, 1):
        print(f"Connection {i}: {flow:.2f} units")

    # Verify the solution
    print("\nVerification:")
    verification = np.dot(A, x)
    print("Ax =", verification)
    print("b  =", b)
    print("\nIs solution correct?", np.allclose(verification, b))
else:
    print("Matrix is not invertible. The system may have no unique solution.")

# Additional analysis
print("\nNetwork Analysis:")
total_flow = np.sum(x)
print(f"Total data flow in the network: {total_flow:.2f} units")
max_flow = np.max(x)
max_flow_connection = np.argmax(x) + 1
print(f"Connection with highest data flow: Connection {max_flow_connection} ({max_flow:.2f} units)")
min_flow = np.min(x)
min_flow_connection = np.argmin(x) + 1
print(f"Connection with lowest data flow: Connection {min_flow_connection} ({min_flow:.2f} units)")


Determinant of matrix A: 225.00

Solution (Data flow through each connection):
Connection 1: -23.87 units
Connection 2: 137.60 units
Connection 3: -336.00 units
Connection 4: 242.53 units
Connection 5: 241.87 units

Verification:
Ax = [200. 300. 150. 120. 250.]
b  = [200 300 150 120 250]

Is solution correct? True

Network Analysis:
Total data flow in the network: 262.13 units
Connection with highest data flow: Connection 4 (242.53 units)
Connection with lowest data flow: Connection 3 (-336.00 units)


Problem 3

In [12]:
import numpy as np

# Define the coefficient matrix A
# Each row represents a cryptographic transformation equation
A = np.array([
    [2, 1, -1, 3, 0, 2, 1],
    [1, 3, 2, -1, 4, 0, 2],
    [3, -2, 4, 1, 0, 1, -1],
    [1, 0, -1, 2, 3, 1, 4],
    [2, 3, 1, -1, 2, 0, 3],
    [0, 1, 3, 2, -1, 4, 2],
    [4, -1, 2, 0, 1, 3, -2]
])

# Define the constants vector b
# These represent the results of each transformation
b = np.array([10, 8, 15, 20, 12, 18, 9])

# Check if matrix is invertible
det = np.linalg.det(A)
print(f"Determinant of transformation matrix: {det:.2f}")

if det != 0:
    # Calculate inverse of A
    A_inv = np.linalg.inv(A)

    # Solve for x using x = A^(-1)b
    x = np.dot(A_inv, b)

    print("\nSolution (Cryptographic transformation variables):")
    for i, var in enumerate(x, 1):
        print(f"Variable {i}: {var:.4f}")

    # Verify the solution
    print("\nVerification:")
    verification = np.dot(A, x)
    print("Ax =", verification)
    print("b  =", b)
    print("\nIs solution correct?", np.allclose(verification, b))

    # Cryptographic interpretation
    print("\nCryptographic Interpretation:")
    print("These values represent the weights or coefficients of different")
    print("cryptographic operations in the algorithm. For example:")
    print(f"- Operation 1 has a weight of {x[0]:.4f}")
    print(f"- Operation 2 has a weight of {x[1]:.4f}")
    print("... and so on.")
    print("\nThese weights determine how each operation contributes to the")
    print("overall transformation of the input in the cryptographic algorithm.")
else:
    print("Transformation matrix is not invertible. The cryptographic system may be flawed or underdetermined.")

# Security analysis
print("\nSecurity Analysis:")
max_weight = np.max(np.abs(x))
max_weight_op = np.argmax(np.abs(x)) + 1
print(f"Operation with highest impact: Operation {max_weight_op} (weight: {max_weight:.4f})")
min_weight = np.min(np.abs(x))
min_weight_op = np.argmin(np.abs(x)) + 1
print(f"Operation with lowest impact: Operation {min_weight_op} (weight: {min_weight:.4f})")
print("\nNote: Operations with higher weights have more influence on the")
print("cryptographic transformation and may be more critical for security.")


Determinant of transformation matrix: -14246.00

Solution (Cryptographic transformation variables):
Variable 1: 2.0733
Variable 2: -1.7380
Variable 3: 1.7915
Variable 4: 1.0636
Variable 5: 0.1481
Variable 6: 1.0889
Variable 7: 4.0145

Verification:
Ax = [10.  8. 15. 20. 12. 18.  9.]
b  = [10  8 15 20 12 18  9]

Is solution correct? True

Cryptographic Interpretation:
These values represent the weights or coefficients of different
cryptographic operations in the algorithm. For example:
- Operation 1 has a weight of 2.0733
- Operation 2 has a weight of -1.7380
... and so on.

These weights determine how each operation contributes to the
overall transformation of the input in the cryptographic algorithm.

Security Analysis:
Operation with highest impact: Operation 7 (weight: 4.0145)
Operation with lowest impact: Operation 5 (weight: 0.1481)

Note: Operations with higher weights have more influence on the
cryptographic transformation and may be more critical for security.


Problem 4

In [8]:
# Step 1: Define the coefficient matrix A (5x5 matrix) with the actual values
A = np.array([
    [2, 3, 1, 4, 5],
    [1, 2, 3, 4, 2],
    [3, 4, 5, 6, 7],
    [4, 5, 6, 7, 8],
    [2, 4, 1, 3, 5]
])

# Step 2: Define the constant matrix B (5x1 matrix) with the actual values
B = np.array([100, 200, 300, 400, 500])

# Step 3: Check if matrix A is invertible (determinant should not be zero)
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A == 0:
    print("Matrix A is singular and cannot be inverted!")
else:
    # Step 4: Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Step 5: Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    # Step 6: Display the solution (unknowns)
    print("Solution (Unknowns):")
    print(X)

Determinant of A: -30.000000000000004
Solution (Unknowns):
[-133.33333333  293.33333333   80.         -106.66666667  -33.33333333]


Problem 5

In [15]:
import numpy as np

def solve_network_routing(A, B):
    """
    Solves the network routing problem using matrix inversion.

    Args:
    A (np.array): Coefficient matrix
    B (np.array): Constants vector

    Returns:
    np.array: Solution vector
    """
    # Check if matrix A is invertible
    det_A = np.linalg.det(A)

    if det_A == 0:
        raise ValueError("Matrix A is singular and cannot be inverted!")

    # Find the inverse of matrix A
    A_inv = np.linalg.inv(A)

    # Solve for X using the matrix inverse method
    X = np.dot(A_inv, B)

    return X

def print_results(X):
    """
    Prints the results of the network routing problem.

    Args:
    X (np.array): Solution vector
    """
    print("Solution (Data flow through each server):")
    for i, flow in enumerate(X, 1):
        print(f"Server {i}: {flow:.2f} units")

def verify_solution(A, X, B):
    """
    Verifies the solution by comparing AX with B.

    Args:
    A (np.array): Coefficient matrix
    X (np.array): Solution vector
    B (np.array): Constants vector

    Returns:
    bool: True if the solution is correct, False otherwise
    """
    verification = np.dot(A, X)
    print("\nVerification:")
    print("Left-hand side (AX):", verification)
    print("Right-hand side (B):", B)
    return np.allclose(verification, B)

# Main execution
if __name__ == "__main__":
    # Define the coefficient matrix A
    A = np.array([
        [5, 3, 1, 1, 0],
        [4, 6, 2, 0, 1],
        [2, 7, 3, 1, 0],
        [1, 2, 4, 5, 0],
        [3, 4, 5, 0, 6]
    ])

    # Define the constants vector B
    B = np.array([200, 300, 150, 120, 250])

    try:
        # Solve the system
        X = solve_network_routing(A, B)

        # Print results
        print_results(X)

        # Verify solution
        is_correct = verify_solution(A, X, B)
        print(f"\nIs the solution correct? {is_correct}")

        # Additional analysis
        print("\nNetwork Analysis:")
        total_flow = np.sum(X)
        print(f"Total data flow in the network: {total_flow:.2f} units")
        max_flow = np.max(X)
        max_flow_server = np.argmax(X) + 1
        print(f"Server with highest data flow: Server {max_flow_server} ({max_flow:.2f} units)")
        min_flow = np.min(X)
        min_flow_server = np.argmin(X) + 1
        print(f"Server with lowest data flow: Server {min_flow_server} ({min_flow:.2f} units)")

    except ValueError as e:
        print(f"Error: {e}")

Solution (Data flow through each server):
Server 1: -23.87 units
Server 2: 137.60 units
Server 3: -336.00 units
Server 4: 242.53 units
Server 5: 241.87 units

Verification:
Left-hand side (AX): [200. 300. 150. 120. 250.]
Right-hand side (B): [200 300 150 120 250]

Is the solution correct? True

Network Analysis:
Total data flow in the network: 262.13 units
Server with highest data flow: Server 4 (242.53 units)
Server with lowest data flow: Server 3 (-336.00 units)
